### ISSUE TITLE
Getting a attribute error "AttributeError: 'super' object has no attribute 'rel'"

### ISSUE THREAD

**Issue by grvmeratwal** [chujiezheng/DiffKS#2]
11:13:38 seq2seq.py[line:71] epoch 1 batch 2100 : gen loss=143.587509

11:21:53 seq2seq.py[line:71] epoch 1 batch 2200 : gen loss=145.715424

11:30:07 seq2seq.py[line:71] epoch 1 batch 2300 : gen loss=131.961563

11:30:31 seq2seq.py[line:110] eval free-run

0%| | 0/244 [00:00<?, ?it/s] 0%| | 0/244 [00:00<?, ?it/s]

wordvec cannot cover 0.017746 vocab

train set restart, 2303 batches and 6 left

dev set restart, 243 batches and 4 left

Traceback (most recent call last):

File "run.py", line 105, in <module>

main(args)

File "/home/user/DiffKS/main.py", line 69, in main

model.train_process()

File "/home/user/DiffKS/seq2seq.py", line 94, in train_process

bleu = self.test('dev', False)['bleu-4']

File "/home/user/DiffKS/seq2seq.py", line 117, in test

self.net.detail_forward(incoming)

File "/home/user/DiffKS/network.py", line 91, in detail_forward

self.connectLayer.detail_forward_disentangle(incoming)

File "/home/user/DiffKS/network.py", line 436, in detail_forward_disentangle

incoming.acc.rel.append(torch.index_select(self.beta, 0, incoming.state.reverse_valid_sen).cpu().tolist())

File "/home/user/DiffKS/utils/storage.py", line 11, in __getattr__

return getattr(super(Storage, self), key)

AttributeError: 'super' object has no attribute 'rel'

**Comment by grvmeratwal** [comment]
I am training model with following platform configuration
ubuntu16.04
python3.7
cuda10.1
cudnn7.6
pytorch1.5.1

**Comment by chujiezheng** [comment]
It is a useless code line. I have deleted it.

**Comment by grvmeratwal** [comment]
ok thanks for support
